### ISSUE TITLE
Profile page not found!!!

### ISSUE THREAD

**Issue by Chayapol-c** [kinkinkinxd/YourFitnessPal#35]
A profile page not found if the user doesn't log in.
I think it needs to merge from branch `user-profile` first.

<img width="780" alt="Screen Shot 2563-11-29 at 23 20 14" src="https://user-images.githubusercontent.com/59835553/100547456-7177e500-3299-11eb-99d3-b6d32a96ccbd.png">

**Comment by PanitanPlengkham** [comment]
We are working on it thank you.

**Comment by jeanyjean** [comment]
Fixed
