### ISSUE TITLE
URLs appear after inputting the wrong url.

### ISSUE THREAD

**Issue by Sahadporn** [kinkinkinxd/YourFitnessPal#37]
I tried inputting random url. It display urls for this project.
Try setting the DEBUG in your setting.py to False.

![image](https://user-images.githubusercontent.com/59825486/100909045-cec0a000-34fe-11eb-9396-e9eb332120b5.png)

**Comment by jeanyjean** [comment]
Thanks for the suggestion. It is fixed.
