### ISSUE TITLE
Minor UI issue. 

### ISSUE THREAD

**Issue by Sahadporn** [kinkinkinxd/YourFitnessPal#39]
url: https://your-fitnesspal.herokuapp.com/profile/edit/

When I click the Physicality Info the tab still highlight on the Basic Info.

![image](https://user-images.githubusercontent.com/59825486/100920917-65488d80-350e-11eb-8b5b-5e357f5202a0.png)
![image](https://user-images.githubusercontent.com/59825486/100921236-d9833100-350e-11eb-8372-7aa515d3d532.png)

**Comment by jeanyjean** [comment]
Fixed it and Thanks.
